apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    app: appointment-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8001"
spec:
  type: NodePort
  selector:
    app: appointment-service
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
