apiVersion: v1
kind: Service
metadata:
  name: billing-service
  labels:
    app: billing-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "metrics"
    prometheus.io/port: "8002"
spec:
  selector:
    app: billing-service
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8002
      targetPort: 8002
    
