apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8003

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8003"
spec:
  selector:
    app: notification-service
  type: NodePort 
  ports:
    - name: http
      protocol: TCP
      port: 8003
      targetPort: 8003

