name: Python Microservices Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [appointment_service, billing_service, notification_service, user_service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies for ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Pytest for ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: pytest tests/
